//This file is autogenerated by the python_src/extract_test_cases.py script, do not modify this manually, as it will be lost.
#include "run_unit_tests.h"
#include <mpi.h>
#include "unity_fixture.h"


void run_all_unit_tests(void)
{
	int participate;
	participate = change_test_world_size(1);
	if (participate!=0 && participate != 1) {return;}
	if (participate==1)
	{
		RUN_TEST_GROUP(string_handling);
		RUN_TEST_GROUP(file_creation_w1_4);
		RUN_TEST_GROUP(read_and_write_single_w1_3_6);
		RUN_TEST_GROUP(read_write_array_w1_4);
		RUN_TEST_GROUP(convenience_api_w1_3);
	}
	participate = change_test_world_size(2);
	if (participate!=0 && participate != 1) {return;}
	if (participate==1)
	{
		RUN_TEST_GROUP(communicate_density_fields_w2);
		RUN_TEST_GROUP(calc_non_bonded_energy_w2);
	}
	participate = change_test_world_size(3);
	if (participate!=0 && participate != 1) {return;}
	if (participate==1)
	{
		RUN_TEST_GROUP(read_and_write_single_w1_3_6);
		RUN_TEST_GROUP(convenience_api_w1_3);
	}
	participate = change_test_world_size(4);
	if (participate!=0 && participate != 1) {return;}
	if (participate==1)
	{
		RUN_TEST_GROUP(file_creation_w1_4);
		RUN_TEST_GROUP(read_write_array_w1_4);
	}
	participate = change_test_world_size(6);
	if (participate!=0 && participate != 1) {return;}
	if (participate==1)
	{
		RUN_TEST_GROUP(read_and_write_single_w1_3_6);
	}
	participate = change_test_world_size(8);
	if (participate!=0 && participate != 1) {return;}
	if (participate==1)
	{
		RUN_TEST_GROUP(communicate_density_fields_w8);
	}
}

